In [1]:
import numpy as np
import math
np.random.seed = 42

In [2]:
weights = np.random.rand(1,3)
weights.shape

(1, 3)

(1, 3)

In [3]:
class ANN:
    def __init__(self, X, y):
        self.x = X
        self.y = y
        self.y_predect = np.zeros(y.shape)
        self.weights = np.random.rand(self.x.shape[1],1)
    def sigmoid( self,z):
        sig = 1 / (1 + np.exp(-z))
        return sig
        
    def sigmoid_derivative(self, p):
        return self.sigmoid(p) * (1 - self.sigmoid(p))
        
    def feedforward(self):
        self.layer = self.sigmoid(np.dot(self.x, self.weights))
        return self.layer
        
    def backprop(self):
        self.error = self.y - self.y_predect
        self.weights = self.weights + np.dot(self.x.T, (2*(self.error)*self.sigmoid_derivative(self.y_predect)))
  
    def fit(self, iterations, verbose=1):
        for i in range(iterations):
                if verbose==1 and i%100==0:
                    print("Iteration ",i)
                    print("y_Actual:",self.y)
                    print("y_Predicted:",self.y_predect)
                    print("loss:")
                    print(np.mean(np.square(y - self.feedforward())))
                self.y_predect = self.feedforward()
                self.backprop()

In [4]:
X = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1],
], dtype=float)


y = np.array([
    [0],
    [1],
    [1],
    [0],
], dtype=float)


print('X:\n', X, '\n')
print('y:\n', y)
print(y.shape)

X:
 [[0. 0. 1.]
 [1. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]] 

y:
 [[0.]
 [1.]
 [1.]
 [0.]]
(4, 1)
X:
 [[0. 0. 1.]
 [1. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]] 

y:
 [[0.]
 [1.]
 [1.]
 [0.]]
(4, 1)


In [5]:
model = ANN(X, y)
model.fit(iterations=1000, verbose=1)

Iteration  0
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.]
 [0.]
 [0.]
 [0.]]
loss:
0.23662781307635927
Iteration  100
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.03722726]
 [0.96898554]
 [0.9796591 ]
 [0.02446958]]
loss:
0.0008235178897209064
Iteration  200
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.01847648]
 [0.9844871 ]
 [0.98979109]
 [0.01217175]]
loss:
0.00020651452919447766
Iteration  300
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.0122547 ]
 [0.98968154]
 [0.99319271]
 [0.00809006]]
loss:
9.149319128467956e-05
Iteration  400
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.00916021]
 [0.99227551]
 [0.99489564]
 [0.00605606]]
loss:
5.1318035525373786e-05
Iteration  500
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.0073109 ]
 [0.99382921]
 [0.9959176 ]
 [0.00483854]]
loss:
3.2769211468180854e-05
Iteration  600
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.00608175]
 [0.9948634 ]
 [0.99659885]
 [0.00402826]]
loss:
2.2715499087517203e

In [14]:
class ANN:
    def __init__(self, X, y, num_hidden_nodes):
        self.x = X
        self.y = y
        self.y_predect = np.zeros(y.shape)
        self.weights1= np.random.rand(self.x.shape[1],num_hidden_nodes) # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(num_hidden_nodes,1)
        
    def sigmoid( self,z):
        sig = 1 / (1 + np.exp(-z))
        return sig
        
    def sigmoid_derivative(self, p):
        return self.sigmoid(p) * (1 - self.sigmoid(p))
        
    def feedforward(self):
        self.layer1 = self.sigmoid(np.dot(self.x, self.weights1))
        self.layer2 = self.sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2
        
    def backprop(self):
        self.error = self.y - self.y_predect
        self.weights2 = self.weights2 + np.dot(self.layer1.T, (2*(self.error)*self.sigmoid_derivative(self.y_predect)))
        self.weights1 = self.weights1 + np.dot(self.x.T, np.dot(2*(self.error)*self.sigmoid_derivative(self.y_predect),self.weights2.T)
                            *self.sigmoid_derivative(self.layer1))
  
    def fit(self, iterations, verbose=1):
        for i in range(iterations):
                if verbose==1 and i%100==0:
                    print("Iteration ",i)
                    print("y_Actual:",self.y)
                    print("y_Predicted:",self.y_predect)
                    print("loss:")
                    print(np.mean(np.square(y - self.feedforward())))
                self.y_predect = self.feedforward()
                self.backprop()

In [15]:
X = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1],
], dtype=float)


y = np.array([
    [0],
    [1],
    [1],
    [0],
], dtype=float)


print('X:\n', X, '\n')
print('y:\n', y)

X:
 [[0. 0. 1.]
 [1. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]] 

y:
 [[0.]
 [1.]
 [1.]
 [0.]]
X:
 [[0. 0. 1.]
 [1. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]] 

y:
 [[0.]
 [1.]
 [1.]
 [0.]]


In [16]:
model = ANN(X, y, 8)
model.fit(iterations=1000, verbose=1)

Iteration  0
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.]
 [0.]
 [0.]
 [0.]]
loss:
0.4356840448175771
Iteration  100
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.01553048]
 [0.98268586]
 [0.98750824]
 [0.01239126]]
loss:
0.00020596549861761298
Iteration  200
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.00565137]
 [0.99357155]
 [0.99518941]
 [0.00471493]]
loss:
2.9281790717760657e-05
Iteration  300
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.0033652 ]
 [0.99608703]
 [0.99706906]
 [0.00290589]]
loss:
1.0831613921502763e-05
Iteration  400
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.00237125]
 [0.99718975]
 [0.99790641]
 [0.00210555]]
loss:
5.552395089083757e-06
Iteration  500
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.00181983]
 [0.99780763]
 [0.99837783]
 [0.00165435]]
loss:
3.3566109789952383e-06
Iteration  600
y_Actual: [[0.]
 [1.]
 [1.]
 [0.]]
y_Predicted: [[0.00147074]
 [0.99820274]
 [0.99867934]
 [0.00136444]]
loss:
2.241524070118329e-